Models/ErrorViewModel.cs
namespace Team_Turtle.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Program.cs
using System.ComponentModel.DataAnnotations;

namespace Team_Turtle.Models
{
    public class Program
    {
        [Key]
        public int ProgramId { get; set; }
        public string? ProgramName { get; set; }
        public int? Length { get; set; }

        // Navigation properties
        public ICollection<Student> Students { get; set; }
    }
}

Models/SignUpViewModel.cs
namespace Team_Turtle.Models
{
	public class SignUpViewModel
	{
		public Student? Student { get; set; }
		public IEnumerable<Program>? Programs { get; set; }
	}
}

Models/Student.cs
using System.ComponentModel.DataAnnotations;
using Team_Turtle.Models.Validation;

namespace Team_Turtle.Models
{
    public class Student
    {
        [Key]
        public int StudentId { get; set; }

        [Required(ErrorMessage = "The email value is required")]
        [EmailValidationAttribute]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Please set your password")]
        public string? Password { get; set; }

        [Required(ErrorMessage = "The name value is required")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please select your program")]
        public int? ProgramId { get; set; }

        [Required(ErrorMessage = "Please select your level")]
        public int? Level { get; set; }

        // Navigation properties
        public Program? Program { get; set; }
    }
}

Models/StudyGroupPost.cs
using System.ComponentModel.DataAnnotations;

namespace Team_Turtle.Models
{
    public class StudyGroupPost
    {
        [Key]
        public int PostId { get; set; }
        public int CreaterId { get; set; }
        public Student? Student { get; set; } 

        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateTime PostedDate { get; set; }
        public List<string>? Members { get; set; }
        public string? ZoomLink { get; set; }
        public string? DiscordLink { get; set; }

    }
}

Models/Validation/EmailValidationAttribute.cs
using System.ComponentModel.DataAnnotations;

namespace Team_Turtle.Models.Validation
{
    public class EmailValidationAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            string email = value.ToString();
            if (email != null && email.EndsWith("@conestogac.on.ca"))
            {
                return ValidationResult.Success;
            }
            else
            {
                return new ValidationResult("Email must end with @conestogac.on.ca");
            }
        }
    }
}

Controllers/BoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Team_Turtle.Controllers
{
    public class BoardController : Controller
    // This will control the CRUD of posts for the study group list
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Detail()
        {
            return View();
        }
    }
}

Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Team_Turtle.Models;

namespace Team_Turtle.Controllers
{
    public class FormController : Controller
    // This will controll the login/sign up form and validate the form
    {
		public FormController(SWCDbContext swcDbContext)
		{
			_swcDbContext = swcDbContext;
		}

		[HttpGet]
		public IActionResult GetSignUpForm()
        {
			var viewModel = new SignUpViewModel
			{
				Student = new Student(),
				Programs = _swcDbContext.Programs.ToList()
			};

			return View("SignUp", viewModel);
		}


        [HttpPost]
        public IActionResult CreateNewAccount(Student student)
        {
			if (ModelState.IsValid)
			{
				// fields are valid so add msmt to the DB & save:
				_swcDbContext.Students.Add(student);
				_swcDbContext.SaveChanges();

				TempData["LastActionMessage"] = $"New account ({student.Email}) created successfully!";

				// Redirect back to the all msmts view:
				return RedirectToAction("Index", "Home");
			}
			else
			{
				// there was a validn err so return the HR msmt to the user
				// along with any possible validn err msgs:
				return View("SignUp", student);
			}
		}

		[HttpGet]
		public IActionResult GetLoginForm()
        {
            return View();

        }

		[HttpPost]
        public IActionResult Login()
        {
            return View();

        }

        private SWCDbContext _swcDbContext;
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Team_Turtle.Models;

namespace Team_Turtle.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Board/Detail.cshtml
@{
    ViewData["Title"] = "Study_Group_Detail Page";
}

<div class="row container">
    <div class="col-md-9">
        <h1 class="display-5 mt-3 mb-2">Study Group Title</h1>
        <h6 class="card-subtitle mb-3 text-body-secondary">Posted on Oct/22/2023</h6>
        <p class="card-text pt-2 pb-2">Hi! We're looking for students to study C# together. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <div>
            <span><a href="#" class="card-link">Zoom</a></span>
            <span><a href="#" class="card-link">Discord</a></span>
        </div>
    </div>
    <div class="col-md-3">
        <h6 class="card-subtitle text-body-secondary mt-3 mb-2">Members</h6>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Dany (Leader)</li>
            <li class="list-group-item">Juhwan</li>
        </ul>
    </div>
        

    
</div>

Views/Board/Index.cshtml
@{
    ViewData["Title"] = "Dashboard Page";
}

<div class="grid row g-2 container" style="--bs-columns: 3;">
    <h1 class="display-6">Find Your Study Groups</h1>
    <div class="card col-md-6">
        <div class="card-body">
            <h5 class="card-title">Study Group Title</h5>
            <div class="d-flex justify-content-between">
                <h6 class="card-subtitle mb-2 text-body-secondary">Posted on Oct/22/2023</h6>
                <h6 class="card-subtitle mb-2 text-body-secondary">2 Members</h6>
            </div>
            <p class="card-text">Hi! We're looking for students to study C# together.</p>
            <a href="#" class="card-link">See Detail</a>
        </div>
    </div>
        <div class="card col-md-6">
        <div class="card-body">
            <h5 class="card-title">Study Group Title</h5>
            <div class="d-flex justify-content-between">
                <h6 class="card-subtitle mb-2 text-body-secondary">Posted on Oct/22/2023</h6>
                <h6 class="card-subtitle mb-2 text-body-secondary">2/3</h6>
            </div>
            <p class="card-text">Hi! We're looking for students to study C# together.</p>
            <a href="#" class="card-link">See Detail</a>
        </div>
    </div>
    <div class="card col-md-12">
        <div class="card-body">
            <h5 class="card-title">Study Group Title</h5>
            <div class="d-flex justify-content-between">
                <h6 class="card-subtitle mb-2 text-body-secondary">Posted on Oct/22/2023</h6>
                <h6 class="card-subtitle mb-2 text-body-secondary">2/3</h6>
            </div>
            <p class="card-text">Hi! We're looking for students to study C# together.</p>
            <a href="#" class="card-link">See Detail</a>
        </div>
    </div>
        <div class="card col-md-12">
        <div class="card-body">
            <h5 class="card-title">Study Group Title</h5>
            <div class="d-flex justify-content-between">
                <h6 class="card-subtitle mb-2 text-body-secondary">Posted on Oct/22/2023</h6>
                <h6 class="card-subtitle mb-2 text-body-secondary">2/3</h6>
            </div>
            <p class="card-text">Hi! We're looking for students to study C# together.</p>
            <a href="#" class="card-link">See Detail</a>
        </div>
    </div>
</div>

Views/Form/Login.cshtml
@using Team_Turtle.Models;

@{
    ViewData["Title"] = "Login Page";
}

<h1 class="display-4 m-5 text-center">Welcome Back, Condors!</h1>
<form class="row g-2 m-5" asp-controller="Form" asp-action="Login" method="post"
      enctype="application/x-www-form-urlencoded">
    <div class="col-md-12 form-group">
        <label for="inputEmail" class="form-label">Email</label>
        <input for="inputEmail" type="email" class="form-control" id="inputEmail">
    </div>
    <div class="col-md-12 form-group">
        <label for="inputPassword" class="form-label">Password</label>
        <input for="inputPassword"type="password" class="form-control" id="inputPassword">
    </div>
    <div class="col-md-6 mt-3 form-group">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>

Views/Form/SignUp.cshtml
@using Team_Turtle.Models;
@model SignUpViewModel

@{
	ViewData["Title"] = "Sign_Up Page";
}

<h1 class="display-4 m-5 text-center">Join Us and Study With Condors!</h1>
<form class="row g-2 m-5" asp-controller="Form" asp-action="CreateNewAccount" method="post"
	  enctype="application/x-www-form-urlencoded">

	<div class="col-md-6 form-group">
		<label asp-for="Student.Email" class="form-label">Email</label>
		<input asp-for="Student.Email" type="email" class="form-control" id="Email">
		<span asp-validation-for="Student.Email" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="Student.Password" class="form-label">Password</label>
		<input asp-for="Student.Password" type="password" class="form-control" id="Password">
		<span asp-validation-for="Student.Password" class="text-danger"></span>
	</div>
	<div class="col-12 form-group">
		<label asp-for="Student.Name" class="form-label">Name</label>
		<input asp-for="Student.Name" type="text" class="form-control" id="Name" placeholder="Jane Doe">
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="Student.ProgramId" class="form-label">Program</label>
		<select asp-for="Student.ProgramId" class="form-select" id="inputProgram">
			<option value="" selected>-------</option>
			@foreach (Program p in Model.Programs)
			{
				<option value="@p.ProgramId">@p.ProgramName</option>
			}
			<!-- Options will be driven from the DB -->
		</select>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="Student.Level" class="form-label">Level</label>
		<select asp-for="Student.Level" class="form-select" id="Level">
			<option value="" selected>-------</option>
			@for(int i = 1; i <= 6; i++)
			{
				<option value="i">i</option>
			}
			<!-- Options will be driven from the DB -->
		</select>
	</div>

	<input type="hidden" asp-for="Student.StudentId" />

	<div class="col-md-6 mt-3 form-group">
		<button type="submit" class="btn btn-primary">Sign Up</button>
	</div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome Page";
}

<div class="text-center">
    <h1 class="display-4 m-5">Welcome to Study With Condors!</h1>
    <div>
        <a asp-controller="Form" asp-action="GetLoginForm">Login</a>
        <span> | </span>
        <a asp-controller="Form" asp-action="GetSignUpForm">Sign Up</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Team_Turtle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Team_Turtle.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Study With Condors</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <!--
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    -->

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-center border-top blockquote">
        <div class="container">
            <p class="m-5">PROJECT BY DANY & JUHWAN</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>